name: github action ì‹¤í–‰í•´ë³´ê¸°
on:
  push:
    branches:
      - main

jobs:
  My-deploy-Job:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: /home/ubuntu/2025action

    steps:
      - name: ðŸš€ SSH to EC2 & build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.REMOTE_DIR }}
            pwd
